<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU</Platforms>
    <RootNamespace>Sentinel.Core</RootNamespace>
    <AssemblyName>Sentinel.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.12" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="9.0.0" />
    <PackageReference Include="System.Management" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sentinel.Service" />
    <InternalsVisibleTo Include="Sentinel.Cli" />
    <InternalsVisibleTo Include="Sentinel.Gui" />
    <InternalsVisibleTo Include="Sentinel.Tests" />
    <InternalsVisibleTo Include="Sentinel.Setup" />
  </ItemGroup>

</Project>